/**
 * BondAlgoExecutionToExecutionListener.hpp
 * Listener that bridges algo-execution output into BondExecutionService.
 *
 * IMPORTANT: Per assignment, this should call ExecuteOrder(), not OnMessage().
 *
 * @author Hao Wang
 */

#ifndef BOND_ALGO_EXECUTION_TO_EXECUTION_LISTENER_HPP
#define BOND_ALGO_EXECUTION_TO_EXECUTION_LISTENER_HPP

#include "../base/soa.hpp"
#include "BondExecutionService.hpp"

 /**
  * BondAlgoExecutionToExecutionListener
  * Forwards ExecutionOrder<Bond> generated by the algo layer into ExecutionService.
  */
class BondAlgoExecutionToExecutionListener
    : public ServiceListener< ExecutionOrder<Bond> >
{
public:
    /**
     * @param service Target BondExecutionService.
     */
    BondAlgoExecutionToExecutionListener(BondExecutionService* service)
        : execService(service) {}

    /**
     * On new algo execution, execute it on a market.
     * We use a fixed market here (can be parameterized if needed).
     */
    virtual void ProcessAdd(ExecutionOrder<Bond>& order) override
    {
        execService->ExecuteOrder(order, Market::BROKERTEC);
    }

    virtual void ProcessUpdate(ExecutionOrder<Bond>& order) override
    {
        execService->ExecuteOrder(order, Market::BROKERTEC);
    }

    virtual void ProcessRemove(ExecutionOrder<Bond>& /*order*/) override {}

private:
    BondExecutionService* execService;
};

#endif
